export const CHANGE_STATE_SHOPPING_CART = "CHANGE_STATE_SHOPPING_CART"  
export const CHANGE_STATE_REGISTRATION_FORM = "CHANGE_STATE_REGISTRATION_FORM"
export const CHANGE_STATE_LOGIN_FORM = "CHANGE_STATE_LOGIN_FORM"
export const CHANGE_STATE_USER_PANEL = "CHANGE_STATE_USER_PANEL"