const INSERT_PRODUCT = "INSERT_PRODUCT"
const DELETE_PRODUCT = "DELETE_PRODUCT" 
const UPDATE_QUANTITY = "UPDATE_QUANTITY"
const GENERATE_ORDER = "GENERATE_ORDER"
const CLEAR_CART = "CLEAR_CART"
export {
  INSERT_PRODUCT , DELETE_PRODUCT , UPDATE_QUANTITY , GENERATE_ORDER, CLEAR_CART
}
