export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_CATEGORIES = "GET_CATEGORIES"
export const SET_CATEGORIE_SELECTED = "SET_CATEGORIE_SELECTED"
export const SET_PRODUCT_SELECTED = "SET_PRODUCT_SELECTED"